/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Clasesfiguralabel.FinClase;
import Clasesfiguralabel.Inicio;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.image.ImageObserver;
import java.text.AttributedCharacterIterator;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import Clasesfiguralabel.*;

/**
 *
 * @author mjper
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jddiagramaflujo = new javax.swing.JDialog();
        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jb_circulo = new javax.swing.JButton();
        jb_ovalo = new javax.swing.JButton();
        jb_paralelogramo = new javax.swing.JButton();
        jb_vertical = new javax.swing.JButton();
        jb_rombo = new javax.swing.JButton();
        jb_rectangulo = new javax.swing.JButton();
        jb_resultado = new javax.swing.JButton();
        jb_derecha = new javax.swing.JButton();
        jb_izquierda = new javax.swing.JButton();
        bt_codigo = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_variables1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jpp_paralelogramo = new javax.swing.JPopupMenu();
        jpp_texto_paralelogramo = new javax.swing.JMenuItem();
        jpp_color_paralelogramo = new javax.swing.JMenuItem();
        jpp_ovalo = new javax.swing.JPopupMenu();
        jpp_color_ovalo = new javax.swing.JMenuItem();
        jpp_rombo = new javax.swing.JPopupMenu();
        jpp_texto_rombo = new javax.swing.JMenuItem();
        jpp_color_rombo = new javax.swing.JMenuItem();
        jpp_rectangulo = new javax.swing.JPopupMenu();
        jpp_texto_rectangulo = new javax.swing.JMenuItem();
        jpp_color_rectangulo = new javax.swing.JMenuItem();
        jpp_resultado = new javax.swing.JPopupMenu();
        jpp_color_resultado = new javax.swing.JMenuItem();
        jpp_text0_resultado = new javax.swing.JMenuItem();
        jd_opcion = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        variables = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cb_tiposvariable = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombrevariable = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jd_asignarvariable = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_variables = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        imagen2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_diagramaflujo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jddiagramaflujo.setTitle("Diagrama de flujo");
        jddiagramaflujo.setPreferredSize(new java.awt.Dimension(1670, 865));
        jddiagramaflujo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Figuras");
        panel1.add(jLabel3);
        jLabel3.setBounds(110, 20, 100, 29);

        jb_circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FigurasDiagramaFlujo/Circulo.jpg"))); // NOI18N
        jb_circulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_circuloMouseClicked(evt);
            }
        });
        panel1.add(jb_circulo);
        jb_circulo.setBounds(200, 170, 30, 33);

        jb_ovalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FigurasDiagramaFlujo/Ovalo.jpg"))); // NOI18N
        jb_ovalo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ovaloMouseClicked(evt);
            }
        });
        panel1.add(jb_ovalo);
        jb_ovalo.setBounds(50, 70, 60, 30);

        jb_paralelogramo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FigurasDiagramaFlujo/Paralelogramo.jpg"))); // NOI18N
        jb_paralelogramo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_paralelogramoMouseClicked(evt);
            }
        });
        panel1.add(jb_paralelogramo);
        jb_paralelogramo.setBounds(180, 60, 50, 33);

        jb_vertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FigurasDiagramaFlujo/flecha.jpg"))); // NOI18N
        jb_vertical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_verticalMouseClicked(evt);
            }
        });
        panel1.add(jb_vertical);
        jb_vertical.setBounds(70, 240, 20, 43);

        jb_rombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FigurasDiagramaFlujo/Rombo.jpg"))); // NOI18N
        jb_rombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_romboMouseClicked(evt);
            }
        });
        panel1.add(jb_rombo);
        jb_rombo.setBounds(200, 110, 30, 37);

        jb_rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FigurasDiagramaFlujo/Rectangulo.jpg"))); // NOI18N
        jb_rectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_rectanguloMouseClicked(evt);
            }
        });
        panel1.add(jb_rectangulo);
        jb_rectangulo.setBounds(60, 120, 40, 33);

        jb_resultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FigurasDiagramaFlujo/figuraproceso.jpg"))); // NOI18N
        jb_resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_resultadoMouseClicked(evt);
            }
        });
        panel1.add(jb_resultado);
        jb_resultado.setBounds(60, 170, 40, 45);

        jb_derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FigurasDiagramaFlujo/flechaderecha.jpg"))); // NOI18N
        jb_derecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_derechaMouseClicked(evt);
            }
        });
        panel1.add(jb_derecha);
        jb_derecha.setBounds(120, 250, 40, 23);

        jb_izquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FigurasDiagramaFlujo/izquierda.jpg"))); // NOI18N
        jb_izquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_izquierdaMouseClicked(evt);
            }
        });
        panel1.add(jb_izquierda);
        jb_izquierda.setBounds(200, 250, 30, 31);

        jddiagramaflujo.getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 310, 370));

        bt_codigo.setText("Generar codigo");
        bt_codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_codigoMouseClicked(evt);
            }
        });
        jddiagramaflujo.getContentPane().add(bt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 860, -1, -1));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(null);
        jTabbedPane1.addTab("Diagrama de flujo", panel);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jTabbedPane1.addTab("Codigo C++", jPanel1);

        jddiagramaflujo.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 1300, 830));

        jButton3.setText("Crear Nueva Variable");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jddiagramaflujo.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jl_variables1.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_variables1);

        jddiagramaflujo.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 110, -1));

        jLabel2.setText("Variables");
        jddiagramaflujo.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        jpp_texto_paralelogramo.setText("Asignar Variable");
        jpp_texto_paralelogramo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpp_texto_paralelogramoActionPerformed(evt);
            }
        });
        jpp_paralelogramo.add(jpp_texto_paralelogramo);

        jpp_color_paralelogramo.setText("Color");
        jpp_color_paralelogramo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpp_color_paralelogramoActionPerformed(evt);
            }
        });
        jpp_paralelogramo.add(jpp_color_paralelogramo);

        jpp_color_ovalo.setText("Color");
        jpp_color_ovalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpp_color_ovaloActionPerformed(evt);
            }
        });
        jpp_ovalo.add(jpp_color_ovalo);

        jpp_texto_rombo.setText("Texto");
        jpp_texto_rombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpp_texto_romboActionPerformed(evt);
            }
        });
        jpp_rombo.add(jpp_texto_rombo);

        jpp_color_rombo.setText("Color");
        jpp_color_rombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpp_color_romboActionPerformed(evt);
            }
        });
        jpp_rombo.add(jpp_color_rombo);

        jpp_texto_rectangulo.setText("Texto");
        jpp_texto_rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpp_texto_rectanguloActionPerformed(evt);
            }
        });
        jpp_rectangulo.add(jpp_texto_rectangulo);

        jpp_color_rectangulo.setText("Color");
        jpp_color_rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpp_color_rectanguloActionPerformed(evt);
            }
        });
        jpp_rectangulo.add(jpp_color_rectangulo);

        jpp_color_resultado.setText("Color");
        jpp_color_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpp_color_resultadoActionPerformed(evt);
            }
        });
        jpp_resultado.add(jpp_color_resultado);

        jpp_text0_resultado.setText("Texto");
        jpp_text0_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpp_text0_resultadoActionPerformed(evt);
            }
        });
        jpp_resultado.add(jpp_text0_resultado);

        jd_opcion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Diagrama de flujo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 320));

        jButton2.setText("jButton2");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 200, 320));

        jd_opcion.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 320));

        variables.setBackground(new java.awt.Color(102, 255, 255));
        variables.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Agregar Variable");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        variables.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 130, 20));

        jLabel4.setFont(new java.awt.Font("Stencil", 3, 24)); // NOI18N
        jLabel4.setText("Variables");
        variables.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        cb_tiposvariable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "int", "char", "bool", "float", "unsigned short int", "short int", "unsigned long int", "long int", "unsigned int" }));
        variables.getContentPane().add(cb_tiposvariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setText("Tipo de variable");
        variables.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setText("Nombre");
        variables.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 60, -1));
        variables.getContentPane().add(tf_nombrevariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 140, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/C-1-400x400.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        variables.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jd_asignarvariable.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_variables.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_variables);

        jd_asignarvariable.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel9.setText("Asignar");
        jd_asignarvariable.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, -1));

        jButton5.setText("Asignar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jd_asignarvariable.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/C-1-400x400.jpg"))); // NOI18N
        imagen2.setText("jLabel8");
        jd_asignarvariable.getContentPane().add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eleccion de diagramas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diagrama-de-flujo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 607));

        jMenu1.setText("Archivo");

        jmi_diagramaflujo.setText("Nuevo");
        jmi_diagramaflujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_diagramaflujoMouseClicked(evt);
            }
        });
        jmi_diagramaflujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_diagramaflujoActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_diagramaflujo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_diagramaflujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_diagramaflujoMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jmi_diagramaflujoMouseClicked

    private void jmi_diagramaflujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_diagramaflujoActionPerformed
        // TODO add your handling code here:
        this.jd_opcion.setModal(true);
        jd_opcion.pack();
        jd_opcion.setLocationRelativeTo(this);
        jd_opcion.setVisible(true);

    }//GEN-LAST:event_jmi_diagramaflujoActionPerformed

    private void jb_circuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_circuloMouseClicked
        // TODO add your handling code here:
        JLabel circulo = new JLabel();
        // name.setPreferredSize(new Dimension(50, 100));
        panel.add(circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 640, 760));
        circulo.setLocation(10, 200);
        circulo.setIcon(new javax.swing.ImageIcon("./src/FigurasDiagramaFlujo/Circulo.jpg"));
        circulo.setOpaque(true);
        circulo.setMaximumSize(new java.awt.Dimension(50, 50));
        circulo.setMinimumSize(new Dimension(50, 10));
        circulo.setLocation(new Point(20, 20));
        circulo.setPreferredSize(new Dimension(50, 50));
        circulo.setSize(50, 50);
        circulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((circulo.getLocation().x + evt.getX() - circulo.getWidth() / 2) >= 0
                        && (circulo.getLocation().x + evt.getX() - circulo.getWidth() / 2) <= 1200) {

                    circulo.setLocation(circulo.getLocation().x + evt.getX() - circulo.getWidth() / 2,
                            circulo.getLocation().y + evt.getY() - circulo.getHeight() / 2);

                }// para que no se salga del rango

            }
        });

        circulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evtr) {
                if (evtr.isMetaDown()) {
                    System.out.println("hola");
                }
            }
        });

        /*
          Ovalo.setBackground(Color.red);
        
        Ovalo.setHorizontalTextPosition(SwingConstants.CENTER);
       
       Ovalo.setOpaque(true);
      
        
       
        
       Ovalo.setBounds(360, 150, 150, 50);
         */

    }//GEN-LAST:event_jb_circuloMouseClicked

    private void jb_ovaloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ovaloMouseClicked
        // TODO add your handling code here:

        if (contovalo == 0) {
            Inicio Ovalo = new Inicio();
            //JLabel Ovalo = new JLabel();
            // name.setPreferredSize(new Dimension(50, 100));
            panel.add(Ovalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 500, 760));
            Ovalo.setLocation(20, 210);
            Ovalo.setIcon(new javax.swing.ImageIcon("./src/Iconitos/Ovalo.png"));

            //Ovalo.setBackground(Color.red);
            Ovalo.setHorizontalTextPosition(SwingConstants.CENTER);

            Ovalo.setOpaque(true);

            Ovalo.setMaximumSize(new java.awt.Dimension(30, 30));
            Ovalo.setMinimumSize(new Dimension(60, 20));
            Ovalo.setLocation(new Point(30, 30));
            Ovalo.setPreferredSize(new Dimension(40, 40));
            Ovalo.setSize(50, 50);
            Ovalo.setBackground(Color.cyan);
            Ovalo.setBounds(440, 320, 100, 50);
            Ovalo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                @Override
                public void mouseDragged(java.awt.event.MouseEvent evt) {
                    if ((Ovalo.getLocation().x + evt.getX() - Ovalo.getWidth() / 2) >= 0
                            && (Ovalo.getLocation().x + evt.getX() - Ovalo.getWidth() / 2) <= 1200) {

                        Ovalo.setLocation(Ovalo.getLocation().x + evt.getX() - Ovalo.getWidth() / 2,
                                Ovalo.getLocation().y + evt.getY() - Ovalo.getHeight() / 2);

                    }// para que no se salga del rango

                }
            });

            Ovalo.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evtr) {
                    if (evtr.isMetaDown()) {
                        //javax.swing.JPopupMenu jpp_paralelogramo1 = new javax.swing.JPopupMenu();

                        jpp_ovalo.show(evtr.getComponent(), evtr.getX(), evtr.getY());
                        tempovalo = Ovalo;

                    }
                }
            });
            Ovalo.setText("Inicio");
            //Ovalo.setBackground(tempovalo.getBackground());
            contovalo++;

        } else if (contovalo == 1) {
            Inicio Ovalo = new Inicio();
            // name.setPreferredSize(new Dimension(50, 100));
            panel.add(Ovalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 500, 760));
            Ovalo.setLocation(20, 210);
            Ovalo.setIcon(new javax.swing.ImageIcon("./src/Iconitos/Ovalo.png"));

            //Ovalo.setBackground(Color.red);
            Ovalo.setHorizontalTextPosition(SwingConstants.CENTER);

            Ovalo.setOpaque(true);

            Ovalo.setMaximumSize(new java.awt.Dimension(30, 30));
            Ovalo.setMinimumSize(new Dimension(60, 20));
            Ovalo.setLocation(new Point(30, 30));
            Ovalo.setPreferredSize(new Dimension(40, 40));
            Ovalo.setSize(50, 50);
            Ovalo.setBackground(Color.cyan);
            Ovalo.setBounds(440, 320, 100, 50);
            Ovalo.setToolTipText("Click derecho para propiedades");
            Ovalo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                @Override
                public void mouseDragged(java.awt.event.MouseEvent evt) {
                    if ((Ovalo.getLocation().x + evt.getX() - Ovalo.getWidth() / 2) >= 0
                            && (Ovalo.getLocation().x + evt.getX() - Ovalo.getWidth() / 2) <= 1200) {

                        Ovalo.setLocation(Ovalo.getLocation().x + evt.getX() - Ovalo.getWidth() / 2,
                                Ovalo.getLocation().y + evt.getY() - Ovalo.getHeight() / 2);

                    }// para que no se salga del rango

                }
            });

            Ovalo.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evtr) {
                    if (evtr.isMetaDown()) {
                        //javax.swing.JPopupMenu jpp_paralelogramo1 = new javax.swing.JPopupMenu();

                        jpp_ovalo.show(evtr.getComponent(), evtr.getX(), evtr.getY());
                        tempovalo = Ovalo;

                    }
                }
            });
            Ovalo.setText("Fin");
            contovalo++;
        } else {
            JOptionPane.showMessageDialog(jddiagramaflujo, "Ya no puede ingresar mas de este tipo");
        }
    }//GEN-LAST:event_jb_ovaloMouseClicked

    private void jb_paralelogramoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_paralelogramoMouseClicked
        // TODO add your handling code here:

        Entrada_Salida Paralelogramo = new Entrada_Salida();
        // name.setPreferredSize(new Dimension(50, 100));
        panel.add(Paralelogramo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 500, 760));
        Paralelogramo.setLocation(20, 210);
        //Paralelogramo.setBackground(Color.red);

        Paralelogramo.setHorizontalTextPosition(SwingConstants.CENTER);
        Paralelogramo.setIcon(new javax.swing.ImageIcon("./src/Iconitos/paralelogramo_p.png"));
        Paralelogramo.setOpaque(true);
        Paralelogramo.setMaximumSize(new java.awt.Dimension(30, 30));
        Paralelogramo.setMinimumSize(new Dimension(60, 20));
        Paralelogramo.setLocation(new Point(30, 30));
        Paralelogramo.setPreferredSize(new Dimension(40, 40));
        //Paralelogramo.setSize(180, 200);
        Paralelogramo.setBackground(Color.ORANGE);
        Paralelogramo.setBounds(440, 320, 100, 67);
Paralelogramo.setToolTipText("Click derecho para propiedades");
        Paralelogramo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((Paralelogramo.getLocation().x + evt.getX() - Paralelogramo.getWidth() / 2) >= 0
                        && (Paralelogramo.getLocation().x + evt.getX() - Paralelogramo.getWidth() / 2) <= 1200) {

                    Paralelogramo.setLocation(Paralelogramo.getLocation().x + evt.getX() - Paralelogramo.getWidth() / 2,
                            Paralelogramo.getLocation().y + evt.getY() - Paralelogramo.getHeight() / 2);

                }// para que no se salga del rango

            }
        });

        Paralelogramo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evtr) {
                if (evtr.isMetaDown()) {
                    //javax.swing.JPopupMenu jpp_paralelogramo1 = new javax.swing.JPopupMenu();

                    jpp_paralelogramo.show(evtr.getComponent(), evtr.getX(), evtr.getY());
                    templabelparalelogramo = Paralelogramo;

                }
            }
        });

        Paralelogramo.setText(templabelparalelogramo.getText());
        //Paralelogramo.setBackground(templabelparalelogramo.getBackground());


    }//GEN-LAST:event_jb_paralelogramoMouseClicked

    private void jb_verticalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_verticalMouseClicked
        // TODO add your handling code here:

        JLabel name = new JLabel();
        // name.setPreferredSize(new Dimension(50, 100));
        panel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 300, 600));
        name.setLocation(20, 210);
        name.setIcon(new javax.swing.ImageIcon("./src/FigurasDiagramaFlujo/Flecha.jpg"));
        name.setMaximumSize(new java.awt.Dimension(30, 30));
        name.setMinimumSize(new Dimension(60, 20));
        name.setLocation(new Point(30, 30));
        name.setPreferredSize(new Dimension(40, 40));
        name.setSize(50, 50);
        
        name.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((name.getLocation().x + evt.getX() - name.getWidth() / 2) >= 0
                        && (name.getLocation().x + evt.getX() - name.getWidth() / 2) <= 1200) {

                    name.setLocation(name.getLocation().x + evt.getX() - name.getWidth() / 2,
                            name.getLocation().y + evt.getY() - name.getHeight() / 2);

                }// para que no se salga del rango

            }
        });


    }//GEN-LAST:event_jb_verticalMouseClicked

    private void jb_romboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_romboMouseClicked
        // TODO add your handling code here:

        Condicional rombo = new Condicional();
        // name.setPreferredSize(new Dimension(50, 100));
        panel.add(rombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 600, 600));
        rombo.setLocation(20, 210);

        rombo.setBackground(Color.GREEN);
        rombo.setHorizontalTextPosition(SwingConstants.CENTER);

        rombo.setOpaque(true);
        rombo.setIcon(new javax.swing.ImageIcon("./src/Iconitos/rombo_p.png"));
        rombo.setMaximumSize(new java.awt.Dimension(30, 30));
        rombo.setMinimumSize(new Dimension(60, 20));
        rombo.setLocation(new Point(30, 30));
        rombo.setPreferredSize(new Dimension(40, 40));
        rombo.setSize(50, 50);
        rombo.setBounds(440, 320, 100, 67);
        rombo.setToolTipText("Click derecho para propiedades");
        rombo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((rombo.getLocation().x + evt.getX() - rombo.getWidth() / 2) >= 0
                        && (rombo.getLocation().x + evt.getX() - rombo.getWidth() / 2) <= 1200) {

                    rombo.setLocation(rombo.getLocation().x + evt.getX() - rombo.getWidth() / 2,
                            rombo.getLocation().y + evt.getY() - rombo.getHeight() / 2);

                }// para que no se salga del rango

            }
        });

        rombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evtr) {
                if (evtr.isMetaDown()) {
                    //javax.swing.JPopupMenu jpp_paralelogramo1 = new javax.swing.JPopupMenu();

                    jpp_rombo.show(evtr.getComponent(), evtr.getX(), evtr.getY());
                    temprombo = rombo;

                }
            }
        });
        rombo.setText(temprombo.getText());
        //rombo.setBackground(temprombo.getBackground());


    }//GEN-LAST:event_jb_romboMouseClicked

    private void jb_rectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_rectanguloMouseClicked
        // TODO add your handling code here:

        Procesos rectangulo = new Procesos();
        // name.setPreferredSize(new Dimension(50, 100));
        panel.add(rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 550, 600));
        rectangulo.setLocation(20, 210);
        rectangulo.setBackground(Color.red);
        rectangulo.setForeground(Color.BLACK);

        rectangulo.setOpaque(true);
        rectangulo.setIcon(new javax.swing.ImageIcon("./src/Iconitos/Rectangulo_p.png"));
        rectangulo.setHorizontalTextPosition(SwingConstants.CENTER);

        rectangulo.setMaximumSize(new java.awt.Dimension(30, 30));
        rectangulo.setMinimumSize(new Dimension(60, 20));
        rectangulo.setLocation(new Point(30, 30));
        rectangulo.setPreferredSize(new Dimension(40, 40));
        //name.setSize(70, 50);
        rectangulo.setBounds(440, 320, 100, 67);
        rectangulo.setToolTipText("Click derecho para propiedades");
        rectangulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((rectangulo.getLocation().x + evt.getX() - rectangulo.getWidth() / 2) >= 0
                        && (rectangulo.getLocation().x + evt.getX() - rectangulo.getWidth() / 2) <= 1200) {

                    rectangulo.setLocation(rectangulo.getLocation().x + evt.getX() - rectangulo.getWidth() / 2,
                            rectangulo.getLocation().y + evt.getY() - rectangulo.getHeight() / 2);

                }// para que no se salga del rango

            }
        });
        rectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evtr) {
                if (evtr.isMetaDown()) {
                    //javax.swing.JPopupMenu jpp_paralelogramo1 = new javax.swing.JPopupMenu();

                    jpp_rectangulo.show(evtr.getComponent(), evtr.getX(), evtr.getY());
                    temprectangulo = rectangulo;

                }
            }
        });

        rectangulo.setText(temprectangulo.getText());
        //rectangulo.setBackground(temprectangulo.getBackground());


    }//GEN-LAST:event_jb_rectanguloMouseClicked

    private void jb_resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_resultadoMouseClicked
        // TODO add your handling code here:

        Imprimir resultado = new Imprimir();
        // name.setPreferredSize(new Dimension(50, 100));
        panel.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 330, 600));
        resultado.setLocation(20, 210);
        resultado.setIcon(new javax.swing.ImageIcon("./src/Iconitos/resultado_p.png"));
        resultado.setMaximumSize(new java.awt.Dimension(30, 30));
        resultado.setMinimumSize(new Dimension(60, 20));
        resultado.setLocation(new Point(30, 30));
        resultado.setHorizontalTextPosition(SwingConstants.CENTER);
        resultado.setOpaque(true);
        resultado.setPreferredSize(new Dimension(40, 40));
        resultado.setBackground(Color.PINK);
        resultado.setBounds(420, 300, 100, 67);
        resultado.setToolTipText("Click derecho para propiedades");
        resultado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((resultado.getLocation().x + evt.getX() - resultado.getWidth() / 2) >= 0
                        && (resultado.getLocation().x + evt.getX() - resultado.getWidth() / 2) <= 1200) {

                    resultado.setLocation(resultado.getLocation().x + evt.getX() - resultado.getWidth() / 2,
                            resultado.getLocation().y + evt.getY() - resultado.getHeight() / 2);

                }// para que no se salga del rango

            }
        });
        resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evtr) {
                if (evtr.isMetaDown()) {
                    //javax.swing.JPopupMenu jpp_paralelogramo1 = new javax.swing.JPopupMenu();

                    jpp_resultado.show(evtr.getComponent(), evtr.getX(), evtr.getY());
                    tempresultado = resultado;

                }
            }
        });

        resultado.setText(tempresultado.getText());


    }//GEN-LAST:event_jb_resultadoMouseClicked

    private void jb_derechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_derechaMouseClicked
        // TODO add your handling code here:
        JLabel derecha = new JLabel();
        // name.setPreferredSize(new Dimension(50, 100));
        panel.add(derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 330, 600));
        derecha.setLocation(20, 210);
        derecha.setIcon(new javax.swing.ImageIcon("./src/FigurasDiagramaFlujo/flechaderecha.jpg"));
        derecha.setMaximumSize(new java.awt.Dimension(30, 30));
        derecha.setMinimumSize(new Dimension(60, 20));
        derecha.setLocation(new Point(30, 30));
        derecha.setPreferredSize(new Dimension(40, 40));
        derecha.setSize(50, 50);

        derecha.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((derecha.getLocation().x + evt.getX() - derecha.getWidth() / 2) >= 0
                        && (derecha.getLocation().x + evt.getX() - derecha.getWidth() / 2) <= 1200) {

                    derecha.setLocation(derecha.getLocation().x + evt.getX() - derecha.getWidth() / 2,
                            derecha.getLocation().y + evt.getY() - derecha.getHeight() / 2);

                }// para que no se salga del rango

            }
        });

    }//GEN-LAST:event_jb_derechaMouseClicked

    private void bt_codigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_codigoMouseClicked
        // TODO add your handling code here:
        /*this.codigogenerado.setModal(true);
        codigogenerado.pack();
        codigogenerado.setLocationRelativeTo(this);
        codigogenerado.setVisible(true);*/

        System.out.println(codigo);


    }//GEN-LAST:event_bt_codigoMouseClicked

    private void jpp_texto_paralelogramoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpp_texto_paralelogramoActionPerformed
        // TODO add your handling code here:
        this.jd_asignarvariable.setModal(true);
        jd_asignarvariable.pack();
        jd_asignarvariable.setLocationRelativeTo(this);
        jd_asignarvariable.setVisible(true);
        
        
        /*String texto = JOptionPane.showInputDialog(this, "Ingrese un texto");
        templabelparalelogramo.setText(texto);
        codigo += "\n"
                + "printf(" + templabelparalelogramo.getText() + ")";*/


    }//GEN-LAST:event_jpp_texto_paralelogramoActionPerformed

    private void jpp_color_paralelogramoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpp_color_paralelogramoActionPerformed
        // TODO add your handling code here:
        Color cl = JColorChooser.showDialog(jddiagramaflujo, "Seleccione Color ", Color.yellow);

        templabelparalelogramo.setBackground(cl);
    }//GEN-LAST:event_jpp_color_paralelogramoActionPerformed

    private void jpp_color_ovaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpp_color_ovaloActionPerformed
        // TODO add your handling code here:
        Color cl = JColorChooser.showDialog(jddiagramaflujo, "Seleccione Color ", Color.yellow);

        tempovalo.setBackground(cl);
    }//GEN-LAST:event_jpp_color_ovaloActionPerformed

    private void jpp_texto_romboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpp_texto_romboActionPerformed
        // TODO add your handling code here:
        String texto = JOptionPane.showInputDialog(jddiagramaflujo, "Ingrese un texto");
        temprombo.setText(texto);
        codigo += "\n"
                + "if(" + temprombo.getText() + "){";
    }//GEN-LAST:event_jpp_texto_romboActionPerformed

    private void jpp_color_romboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpp_color_romboActionPerformed
        // TODO add your handling code here:
        Color cl = JColorChooser.showDialog(jddiagramaflujo, "Seleccione Color ", Color.yellow);

        temprombo.setBackground(cl);
    }//GEN-LAST:event_jpp_color_romboActionPerformed

    private void jb_izquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_izquierdaMouseClicked
        // TODO add your handling code here:
        JLabel izquierda = new JLabel();
        // name.setPreferredSize(new Dimension(50, 100));
        panel.add(izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 300, 600));
        izquierda.setLocation(20, 210);
        izquierda.setIcon(new javax.swing.ImageIcon("./src/FigurasDiagramaFlujo/izquierda.jpg"));
        izquierda.setMaximumSize(new java.awt.Dimension(30, 30));
        izquierda.setMinimumSize(new Dimension(60, 20));
        izquierda.setLocation(new Point(30, 30));
        izquierda.setPreferredSize(new Dimension(40, 40));
        izquierda.setSize(50, 50);
        izquierda.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((izquierda.getLocation().x + evt.getX() - izquierda.getWidth() / 2) >= 0
                        && (izquierda.getLocation().x + evt.getX() - izquierda.getWidth() / 2) <= 1200) {

                    izquierda.setLocation(izquierda.getLocation().x + evt.getX() - izquierda.getWidth() / 2,
                            izquierda.getLocation().y + evt.getY() - izquierda.getHeight() / 2);

                }// para que no se salga del rango

            }
        });

    }//GEN-LAST:event_jb_izquierdaMouseClicked

    private void jpp_texto_rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpp_texto_rectanguloActionPerformed
        // TODO add your handling code here:
String mensaje = JOptionPane.showInputDialog(jddiagramaflujo, "Ingrese la operacion: ");

temprectangulo.setText(mensaje);
       

    }//GEN-LAST:event_jpp_texto_rectanguloActionPerformed

    private void jpp_color_rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpp_color_rectanguloActionPerformed
        // TODO add your handling code here:
        Color cl = JColorChooser.showDialog(jddiagramaflujo, "Seleccione Color ", Color.yellow);

        temprectangulo.setBackground(cl);
    }//GEN-LAST:event_jpp_color_rectanguloActionPerformed

    private void jpp_color_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpp_color_resultadoActionPerformed
        // TODO add your handling code here:
        Color cl = JColorChooser.showDialog(jddiagramaflujo, "Seleccione Color ", Color.yellow);
        tempresultado.setBackground(cl);
    }//GEN-LAST:event_jpp_color_resultadoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.jddiagramaflujo.setModal(true);
        jddiagramaflujo.pack();
        jddiagramaflujo.setLocationRelativeTo(this);

        // jddiagramaflujo.setMaximumSize(1500, 0x5dc);
        jddiagramaflujo.setVisible(true);
        jd_opcion.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:

        Variable va = new Variable(tf_nombrevariable.getText(), cb_tiposvariable.getSelectedItem().toString());
        listavariables.add(va);

        DefaultListModel modelo = (DefaultListModel) jl_variables.getModel();
        modelo.addElement(va);
        jl_variables.setModel(modelo);
        jl_variables1.setModel(modelo);

        JOptionPane.showMessageDialog(variables, "Variable agregada");


    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.variables.setModal(true);
        variables.pack();
        variables.setLocationRelativeTo(this);
        variables.setVisible(true);

    }//GEN-LAST:event_jButton3MouseClicked

    private void jpp_text0_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpp_text0_resultadoActionPerformed
        // TODO add your handling code here:
         String texto = JOptionPane.showInputDialog(jddiagramaflujo, "Ingrese un texto");
        tempresultado.setText(texto);
    }//GEN-LAST:event_jpp_text0_resultadoActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        
        templabelparalelogramo.getListva().add(jl_variables.getSelectedValue());
        String acum="";
        for (Variable t : templabelparalelogramo.getListva()) {
            acum+=t.getNombre()+",";
        }
        
        templabelparalelogramo.setText("Lea "+acum);
        
        
        
        
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_codigo;
    private javax.swing.JComboBox<String> cb_tiposvariable;
    private javax.swing.JLabel imagen2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_circulo;
    private javax.swing.JButton jb_derecha;
    private javax.swing.JButton jb_izquierda;
    private javax.swing.JButton jb_ovalo;
    private javax.swing.JButton jb_paralelogramo;
    private javax.swing.JButton jb_rectangulo;
    private javax.swing.JButton jb_resultado;
    private javax.swing.JButton jb_rombo;
    private javax.swing.JButton jb_vertical;
    private javax.swing.JDialog jd_asignarvariable;
    private javax.swing.JDialog jd_opcion;
    private javax.swing.JDialog jddiagramaflujo;
    private javax.swing.JList<Variable> jl_variables;
    private javax.swing.JList<Variable> jl_variables1;
    private javax.swing.JMenuItem jmi_diagramaflujo;
    private javax.swing.JMenuItem jpp_color_ovalo;
    private javax.swing.JMenuItem jpp_color_paralelogramo;
    private javax.swing.JMenuItem jpp_color_rectangulo;
    private javax.swing.JMenuItem jpp_color_resultado;
    private javax.swing.JMenuItem jpp_color_rombo;
    private javax.swing.JPopupMenu jpp_ovalo;
    private javax.swing.JPopupMenu jpp_paralelogramo;
    private javax.swing.JPopupMenu jpp_rectangulo;
    private javax.swing.JPopupMenu jpp_resultado;
    private javax.swing.JPopupMenu jpp_rombo;
    private javax.swing.JMenuItem jpp_text0_resultado;
    private javax.swing.JMenuItem jpp_texto_paralelogramo;
    private javax.swing.JMenuItem jpp_texto_rectangulo;
    private javax.swing.JMenuItem jpp_texto_rombo;
    private javax.swing.JPanel panel;
    private java.awt.Panel panel1;
    private javax.swing.JTextField tf_nombrevariable;
    private javax.swing.JDialog variables;
    // End of variables declaration//GEN-END:variables
int contovalo = 0;
    String labelname = "h",
            codigo = "Programa\n"
            + "#include <stdio.h>\n\n"
            + "int main(){\n";
    Entrada_Salida templabelparalelogramo = new Entrada_Salida();
    Inicio tempovalo = new Inicio();
    Condicional temprombo = new Condicional();
    Procesos temprectangulo = new Procesos();
    Imprimir tempresultado = new Imprimir();
    ArrayList listavariables = new ArrayList();
    ArrayList <JLabel> listafiguras= new ArrayList();

}//
